[package]
name = "serde"
version = "0.1.0"
edition = "2021"

[features]
profiler = ["uwheel/profiler"]

[dependencies]
uwheel = { workspace = true, features = ["serde"] }
postcard.workspace = true
lz4_flex.workspace = true
zstd = "0.12.4"
