[package]
name = "aggregator"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
categories.workspace = true
license.workspace = true
readme.workspace = true

[dependencies]
awheel.workspace = true
zerocopy.workspace = true
